### ISSUE TITLE
Support downloading cluster kubeconfig

### ISSUE THREAD

**Issue by stephenthedev** [banzaicloud/banzai-cli#148]
**Is your feature request related to a problem? Please describe.**
Currently the only way to get the Kubeconfig from a cluster is via the UI

**Describe the solution you'd like to see**
A command under the cluster CLI topic to show the kubeconfig

**Describe alternatives you've considered**
I haven't thought about others

**Additional context**
NA

**Comment by hiroshui** [comment]
I think the request in this ticket has been already implemented, because you can use ```banzai cluster config --cluster-name "${CLUSTER_NAME}" --path kubeconfig``` to retrieve the kubeconfig for the specified cluster.

**Comment by orymate** [comment]
Thanks. Solved by #242
