### ISSUE TITLE
404 error on cli suggested token url 

### ISSUE THREAD

**Issue by lalyos** [banzaicloud/banzai-cli#210]
I'm trying to log in with baza-cli, and in the 2. step the url doesn't seem to be correct:

```
> banzai login
? Pipeline endpoint: https://beta.banzaicloud.io/pipeline
? Please copy your Pipeline access token from the token field of https://beta.banzaicloud.io/pipeline/api/v1/token
```

I get a 404 page not found

**Comment by orymate** [comment]
Could you check that you have the latest banzai-cli version installed?
![image](https://user-images.githubusercontent.com/207816/75791309-adaf0100-5d6c-11ea-8c92-07b8056ddc36.png)

**Comment by sagikazarmark** [comment]
This is an old URL, so my guess is also that the CLI is old.

**Comment by lalyos** [comment]
This was the whole process of installation:

1. `curl https://getpipeline.sh | sh` this reported : "banzai-cli is already installed. Run with 'auto' argument to install/upgrade anyway"
2. `curl https://getpipeline.sh | sh -s auto`

That was the point when I had the issue. But at that point I didn't catch that that there was a _warning_ message, so I was missing an extra:

`brew link --overwrite banzai-cli`

**Comment by orymate** [comment]
see https://github.com/banzaicloud/banzai-cli/pull/211#issuecomment-598090918
