### ISSUE TITLE
One liner for cluster creation

### ISSUE THREAD

**Issue by sagikazarmark** [banzaicloud/banzai-cli#293]
**Is your feature request related to a problem? Please describe.**
As a developer who actively work with Kubernetes, I want to create clusters with a single command in 1 second.

As a blog reader, I want short and easy to follow instructions for trying features.

**Describe the solution you'd like to see**
Make it easier to create clusters from the CLI without the use of a cluster.json and the tedious create process.

One possible solution is to add hard-coded, virtual cluster templates to the cli: `banzai cluster create --template dev`.

The user should also be able to view these templates though.

**Describe alternatives you've considered**
Literally anything would be better.

**Comment by balazsbc** [comment]
reuse existing default cluster configuration. 
review current defaults in PKE/EKS on AWS.
add multiple options.
