### ISSUE TITLE
In subshell, cluster deletion with --cluster-name is not working properly

### ISSUE THREAD

**Issue by bartam1** [banzaicloud/banzai-cli#377]
BUILD:  0.21.8
**Describe the bug**
After using "banzai cluster shell..." thus a subshell created. The banzai cluster delete --cluster-name <clusername> does not work properly. It always wants to delete the cluster in the subshell. 

**Steps to reproduce the issue:**
1. banzai cluster shell --cluster-name=clusterName
2. banzai cluster delete --cluster-name anyOtherCluster or  banzai cluster delete anyOtherCluster or banzai cluster delete

**Expected behavior**
It should delete the selected cluster

**Screenshots**
banzai cluster delete --cluster-name otherCluster
Id    Name              Distribution  Location  Version  CreatorName  CreatedAt             Status   StatusMessage
12345 myCurrentCluster ....
? Do you want to DELETE the cluster? No

**Comment by akijakya** [comment]
This behaviour is also true for other specific cluster-related banzai commands (`get`, `node list`, `nodepool list`...), so I conclude this is expected that in a clusters subshell you can only manage that specific cluster and not others.
